### ISSUE TITLE
is AlphaNet a0 ~ a6 exactly same as the a0 ~ a6 in attentative NAS?

### ISSUE THREAD

**Issue by linnanwang** [facebookresearch/AlphaNet#1]
Hello there,

I find a very interesting setup in the AlphaNet/Attentative codebases:

From these configuration files:
https://github.com/facebookresearch/AttentiveNAS/blob/master/configs/eval_attentive_nas_models.yml
https://github.com/facebookresearch/AlphaNet/blob/master/configs/eval_alphanet_models.yml

These networks look exactly the same, am I right? Thanks.

**Comment by dilinwang820** [comment]
Good catch, it should be the same from a0 to a6. In this repo, we only added one additional model in the range of 500-600 MFLOPs to further expand our model family. 

However, as you might noticed:

--- a5 in attentivenas -- 
    a5:        model: "attentive_nas_a5"        resolution: 256        width: [16, 16, 24, 32, 72, 112, 192, 216, 1792]        kernel_size: [3, 3, 3, 5, 3, 3, 3]        expand_ratio: [1, 4, 5, 4, 4, 6, 6]        depth: [1, 3, 3, 3, 4, 6, 1]

--- a5 in alphanet -- 
    a5:        model: "alphanet_a5_small"        resolution: 256        width: [16, 16, 24, 32, 64, 112, 208, 216, 1984]        kernel_size: [3, 3, 3, 3, 3, 5, 3]        expand_ratio: [1, 4, 4, 5, 4, 6, 6]        depth: [1, 3, 3, 4, 4, 5, 1]

These two are obviously different models. 
It's definitely NOT my intention to manually check-pick this model; as you can see from our other models, our performance improvements are quite significantly already. 
For a5 in AttentiveNAS, the corresponding top-1 given by AlphaNet is 80.132, which is slightly lower compared to the results in our paper. 
I guess this happened because these two models have the same FLOPS, and I mistakenly copied the wrong model from my raw log file for evaluation. I have updated the eval_alphanet_models.yml to further clarify on this discrepancy.  
Thanks for your finding.
