### ISSUE TITLE
Why use the training dataset in the test stage?

### ISSUE THREAD

**Issue by howardgriffin** [facebookresearch/AlphaNet#3]
Hi, I check the test_alphanet.py and find it use the training dataset when testing. From your comment 'bn running stats calibration following Slimmable' , does it mean to caculate the training data's mean and variance in BN?
Thank you in advance!

**Comment by howardgriffin** [comment]
I re-read the paper, and found it was actually calibrate the bn statistics of the training data. But why you don't save the BN satistics during training stage?

**Comment by dilinwang820** [comment]
It's impossible to save all BN statistics for all sub-networks, because the total number of possible sub-networks might be millions or billions. 

Please see Universally Slimmable Networks and Improved Training Techniques https://arxiv.org/pdf/1903.05134.pdf for more detailed discussion on the procedure

**Comment by howardgriffin** [comment]
Got it，thank you!
